### 예약 요청
POST localhost:19005/api/v1/reservations
Content-Type: application/json

{
  "user_id": 12345,
  "restaurant_id": "550e8400-e29b-41d4-a716-446655440000",
  "restaurant_schedule_id": "660e8400-e29b-41d4-a716-446655440000",
  "guest_count": 4
}

### 예약 상태 변경
PATCH localhost:19005/api/v1/reservations/status/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

{
  "status": "COMPLETE"
}

### 예약 취소
POST localhost:19005/api/v1/reservations/cancel/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

### 예약 상세 조회
GET localhost:19005/api/v1/reservations/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

### 예약 목록 검색
GET localhost:19005/api/v1/reservations?page=0&size=5&sort=createdAt,DESC&status=PENDING
Content-Type: application/json
