### 예약 요청
POST localhost:19005/api/v1/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0b21lcjEyMzQiLCJ1c2VySWQiOiIzIiwicm9sZSI6IkNVU1RPTUVSIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiaWF0IjoxNzM2NDAxNzM0LCJleHAiOjE3MzY0MDIwOTR9.fAZLuMzp_bM79Nmv1hpOyX7dJ_15Tvdlp_t9DmkREkE

{
  "user_id": 12345,
  "restaurant_id": "57de6c10-88b4-4713-b9f4-a547f144eadf",
  "restaurant_schedule_id": "49e7fb9b-f1cf-4879-9f59-1484380507c7",
  "guest_count": 4,
  "reservation_date": "2025-01-21",
  "reservation_time": "14:00"
}


### 예약 상태 변경
PATCH localhost:19005/api/v1/reservations/status/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

{
  "status": "COMPLETE"
}

### 예약 취소
POST localhost:19005/api/v1/reservations/cancel/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

### 예약 상세 조회
GET localhost:19005/api/v1/reservations/e47cf394-4a51-416c-a2d7-1b45dd17477b
Content-Type: application/json

### 예약 목록 검색
GET localhost:19005/api/v1/reservations?page=0&size=5&sort=createdAt,DESC&status=PENDING
Content-Type: application/json

### 페인 테스트
GET localhost:19005/api/v1/reservations/get-data-feign
Content-Type: application/json