spring:
  application:
    name: restaurant-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/