### 결제 요청
POST localhost:19005/api/v1/payments
Content-Type: application/json

{
  "reservation_id": "a5336d1d-e83a-4801-afee-e44b31fcc670",
  "user_id": 12345,
  "amount": 10000,
  "method": "CARD",
  "pg_name": "TOSS"
}

### 결제 검색
GET localhost:19005/api/v1/payments?page=0&size=5&sort=createdAt,DESC
Content-Type: application/json

### 결제 상태 변경
PATCH localhost:19005/api/v1/payments/status/9f24d789-6e40-42fc-af7a-f2c03cfd5bff
Content-Type: application/json

{
  "status": "REFUND"
}

### 환불 요청
POST localhost:19005/api/v1/payments/refund/393fcd8f-9895-4f4f-9ea8-46ba6e9cd2e2
Content-Type: application/json

### 결제 단건 조회
GET localhost:19005/api/v1/payments/550e8400-e29b-41d4-a716-446655440002
Content-Type: application/json