services:
  eureka-server:
    image: 120569603428.dkr.ecr.ap-northeast-2.amazonaws.com/bobjool/eureka:latest
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_PORT=${EUREKA_PORT}
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}

  gateway:
    image: 120569603428.dkr.ecr.ap-northeast-2.amazonaws.com/bobjool/gateway:latest
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GATEWAY_SERVER_PORT=${GATEWAY_SERVER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - SHARED_REDIS_PORT=${SHARED_REDIS_PORT}
    depends_on:
      - eureka-server