server:
  port: ${EUREKA_PORT:19000}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOSTNAME:bobjool-eureka-lb-160323905.ap-northeast-2.elb.amazonaws.com}
    prefer-ip-address: true
