### 회원가입
POST localhost:19005/api/v1/auths/sign-up
Content-Type: application/json

{
  "username": "customer1234",
  "password": "1234",
  "name": "customername",
  "nickname": "customernick",
  "slackEmail": "customer@slack.com",
  "email": "customer@email.com",
  "phoneNumber": "010-1234-5680",
  "role": "CUSTOMER"
}

### 로그인
POST localhost:19005/api/v1/auths/sign-in
Content-Type: application/json

{
  "username": "customer1234",
  "password": 1234
}